from pathlib import Path
import json,hashlib
root=Path(__file__).resolve().parents[1]
c=json.loads((root/'src/content.json').read_text(encoding='utf8'))
sources={s['id']:s for s in c['sources']}
locations={'divia-ig':'02_Divia_Unpad_TV/divia-ig-performance.jpg; original Edits report page 1','divia-audience':'02_Divia_Unpad_TV/divia-ig-audience.jpg; original Edits report page 2','divia-tiktok':'02_Divia_Unpad_TV/divia-tiktok-growth.jpg; year/date corroborated by training report slide 8','divia-linkedin':'C:/Users/Hp/Downloads/divia-unpad-tv-fikom_content_1785500685838.xls; All posts worksheet; matched by post title and creation date','tiriz-kpi':'01_TIRIZ/TIRIZ_Laporan_Kampanye.pdf p.16, visually verified','tiriz-kol':'01_TIRIZ/TIRIZ_Laporan_Kampanye.pdf p.9, visually verified','certificate':'C:/Users/Hp/Downloads/033_Muhammad Raihan Ramadhan_Sertifikat Google Digital Garage.pdf p.1, visually verified'}
rows=[]
locations['cakradata']='User revision request, October 5, 2026: 13,000 top TikTok views and 2,000 top Instagram views; CV p.1 summary. Exact post dates / raw analytics not independently resolved.'
for m in c['metrics']:
    r={**m,'sourceLocation':locations[m['sourceId']],'definition':m['note'],'status':'verified-original-source','publicUse':'website and new portfolio PDF; account/team attribution retained'}
    if 'target' in m:r['derived']={'percentOfTarget':m['value']/m['target']*100,'percentAboveTarget':(m['value']-m['target'])/m['target']*100,'formula':'actual / target * 100; (actual - target) / target * 100'}
    if m['id']=='li-ctr':r['derived']={'clicks':104,'impressions':160,'formula':'104 / 160 * 100','result':65.0};r['exportRow']='All posts worksheet row 7 (Excel row count including two header rows); June 19 career carousel; Posted by Marcelino Deva'
    if m.get('verification'):r['status']=m['verification'];r['qualifications']='User explicitly confirmed these top-post results in the revision request. Internship period is role context, not a verified analytics date range. Not account totals or follower growth.'
    rows.append(r)
rows.append({**c['audience'],'id':'divia-age-composition','sourceLocation':locations['divia-audience'],'status':'verified-original-source','definition':'Rounded share of account followers per age band, not viewer composition; values sum 100.0%.'})
for p in c['projects']:
    rows.append({'id':p['id']+'-role-actions','publicText':{'category':p['category'],'period':p['period'],'contribution':p['contribution'],'narrative':p['narrative']},'attribution':'Raihan contribution; outcomes qualified separately','sourceLocation':'Supplied CV p.1 + former portfolio relevant case study; Divia training report; TIRIZ original campaign report and content planner','status':'role-summary corroborated by work samples/planners, without causal claim','qualifications':'Cakradata individual per-post ownership not established. Divia LinkedIn export explicitly names Raihan on launch, SOP and article posts; career carousel names teammate. TIRIZ planner contains Raihan-assigned published rows; template laptop sample excluded.'})
for e in c['experience']:
    fikomnex=e['id']=='fikomnex'
    location=('User confirmation, October 5, 2026: Raihan led a two-person sponsorship team that managed media partnerships with five Fikom Unpad student organizations. The existing partnership tracker is additional assignment evidence.' if fikomnex else 'User revision request, October 5, 2026, explicitly supplying responsibilities and results; CV p.2; previous portfolio; supplied event photo. '+('Ideation tracker roster names Raihan as Event Management Staff; whole-committee roster and seven-person delivery team are different groups.' if e['id']=='ideation' else 'Original attendance / individual KPI records not independently reviewed.'))
    qualifications=('User confirms management with five student organizations; this is not a claim that five paid sponsors or completed contracts were independently established. Tracker statuses are not a complete outcome ledger.' if fikomnex else 'Source qualifications retained privately')
    rows.append({'id':e['id']+'-responsibilities','publicText':e,'sourceLocation':location,'status':'user-confirmed role, actions and results','qualifications':qualifications,'attribution':'Student organization/event responsibility, distinct from employment','derived':{'formula':'81 / 92 * 100','result':81/92*100,'display':'approximately 88%'} if e['id']=='hima' else None,'logoAttribution':'BEM Fikom organizer mark used for Fikomnex, not a custom Fikomnex logo' if fikomnex else 'Genuine mark from user public portfolio assets'})
rows.append({'id':'hard-skill-apps','publicText':c['toolGroups'],'sourceLocation':'User revision request, October 5, 2026','status':'user-confirmed tools and scoped proficiency','attribution':'Excel simple data processing; Canva light editing; no invented proficiency ratings'})
rows.extend([{'id':'profile-contact','publicText':c['profile'],'sourceLocation':'CV p.1; Ideation tracker self-contact roster; supplied portrait','status':'verified contact matches both sources; student status from CV','exclude':'Home address, phone and student ID are not repeated in website content. User-requested original CV remains unchanged.'},{'id':'course-completion','publicText':c['certification'],'sourceLocation':locations['certificate'],'status':'visual name/date/course verified','definition':'Completion only. No added accreditation or unverified issuer.'}])
inventory=[]
for folder in sorted(root.parent.glob('[0-9][0-9]_*')):
    for p in sorted(folder.iterdir()):
        if p.is_file():inventory.append({'path':str(p.relative_to(root.parent)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(root/'private/evidence-register.json').write_text(json.dumps({'reviewDate':'2026-10-05','claims':rows,'inputInventory':inventory,'sourceRegistry':c['sources'],'readScope':'See search-scope.md','gaps':'See unresolved-claims.md'},ensure_ascii=False,indent=2),encoding='utf8')
print('Private register:',len(rows),'claim groups;',len(inventory),'original files fingerprinted.')
