import { useEffect, useState } from 'react';
import { content, metric, source, format } from './content';
type Proof=(ids:string[])=>void;
export function useUrlChoice(key:string,values:string[],fallback:string){
  const read=()=>{const v=new URLSearchParams(location.search).get(key);return v&&values.includes(v)?v:fallback;};
  const [value,set]=useState(read);
  useEffect(()=>{const restore=()=>set(read());addEventListener('popstate',restore);return()=>removeEventListener('popstate',restore);},[key]);
  const change=(v:string)=>{const url=new URL(location.href);url.searchParams.set(key,v);history.pushState({},'',url);set(v);};
  return [value,change] as const;
}
export function Tabs({id,values,value,onChange}:{id:string;values:{id:string;label:string}[];value:string;onChange:(v:string)=>void}){
  return <div className="tabs" role="tablist" aria-label={id==='platform'?'Divia platform results':'TIRIZ campaign metrics'}>{values.map((v,i)=><button key={v.id} id={`${id}-${v.id}`} role="tab" aria-selected={value===v.id} aria-controls={`${id}-panel`} tabIndex={value===v.id?0:-1} onClick={()=>onChange(v.id)} onKeyDown={e=>{let j=i;if(e.key==='ArrowRight')j=(i+1)%values.length;else if(e.key==='ArrowLeft')j=(i+values.length-1)%values.length;else if(e.key==='Home')j=0;else if(e.key==='End')j=values.length-1;else return;e.preventDefault();onChange(values[j].id);document.getElementById(`${id}-${values[j].id}`)?.focus();}}>{v.label}</button>)}</div>;
}
function Table({caption,headers,rows}:{caption:string;headers:string[];rows:(string|number)[][]}){
  return <details className="table-alternative"><summary>View data table</summary><div className="table-scroll"><table><caption>{caption}</caption><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=>j===0?<th scope="row" key={j}>{c}</th>:<td key={j}>{c}</td>)}</tr>)}</tbody></table></div></details>;
}
export function MetricTiles({ids}:{ids:string[]}){return <div className="metric-grid">{ids.map(id=>{const m=metric(id);return <div className="metric" key={id}><strong>{m.display}</strong><span>{m.label}</span></div>;})}</div>;}
function ProofReference({id,onProof}:{id:string;onProof:Proof}){return <button className="text-link proof-reference" onClick={()=>onProof([id])}>{source(id).label} <span aria-hidden="true">↗</span></button>;}
function PlatformBars({platform}:{platform:string}){
  if(platform==='linkedin')return null;
  const ids=platform==='instagram'?['ig-views','ig-viewers']:['tt-total','tt-net'];
  return <div className="platform-bars">{ids.map((id,i)=>{const m=metric(id),max=platform==='instagram'?25000:i===0?5000:500;return <div className="platform-bar" key={id}><span>{m.label}</span><svg viewBox="0 0 700 30" role="img" aria-label={`${m.label}: ${m.display}. Scale zero to ${format(max)} ${m.unit}.`}><title>{m.label}: {m.display} {m.unit}</title><rect width="700" height="12" y="5" rx="6" className="chart-track"/><rect width={m.value/max*700} height="12" y="5" rx="6" className="chart-fill"/></svg><span className="caption">0-{format(max)} {m.unit}{platform==='tiktok'?' / separate scale':''}</span></div>;})}</div>;
}
export function PlatformChart({onProof}:{onProof:Proof}){
  const [platform,choose]=useUrlChoice('platform',['instagram','tiktok','linkedin'],'instagram');
  const [tip,setTip]=useState<string|null>(null);
  const id=platform==='instagram'?'divia-ig':platform==='tiktok'?'divia-tiktok':'divia-linkedin';
  const ids=platform==='instagram'?['ig-views','ig-viewers','ig-shares','ig-saves']:platform==='tiktok'?['tt-total','tt-net','tt-comparison']:['li-carousel','li-clicks','li-ctr'];
  const takeaway=platform==='instagram'?'22K Reel views and 11K viewers describe different measures. Rounded K values stay rounded.':platform==='tiktok'?'+31.5% compares net followers with the comparison period. It does not measure total-follower growth.':'The June 19 career carousel recorded 104 clicks from 160 impressions: a 65.0% CTR. This is team content.';
  return <section className="chart-panel platform-chart" onKeyDown={e=>{if(e.key==='Escape')setTip(null);}} aria-labelledby="platform-heading"><div className="chart-heading"><h4 id="platform-heading">One team. Three different measures.</h4><span className="caption">Divia account & team results</span></div><Tabs id="platform" values={[{id:'instagram',label:'Instagram'},{id:'tiktok',label:'TikTok'},{id:'linkedin',label:'LinkedIn'}]} value={platform} onChange={v=>{choose(v);setTip(null);}}/><div id="platform-panel" role="tabpanel" aria-labelledby={`platform-${platform}`} tabIndex={0} className="tab-panel"><p className="chart-period">{source(id).label}</p><div className="interactive-metrics">{ids.map(mid=>{const m=metric(mid);return <button key={mid} className="metric metric-control" aria-describedby={`detail-${mid}`} onMouseEnter={()=>setTip(mid)} onMouseLeave={()=>setTip(null)} onFocus={()=>setTip(mid)} onBlur={()=>setTip(null)} onClick={()=>setTip(mid)}><strong>{m.display}</strong><span>{m.label}</span><span className={tip===mid?'metric-detail':'sr-only'} id={`detail-${mid}`}>{m.note}</span></button>;})}</div><PlatformBars platform={platform}/>{platform==='linkedin'&&<svg className="ctr-track" viewBox="0 0 700 68" role="img" aria-label="65 percent click-through rate, calculated as 104 clicks divided by 160 impressions"><title>Career carousel click-through rate: 65.0%</title><rect x="0" y="8" width="700" height="12" rx="6" className="chart-track"/><rect x="0" y="8" width="455" height="12" rx="6" className="chart-fill"/><text x="0" y="57">0%</text><text x="455" y="57" textAnchor="middle">65.0% CTR</text><text x="700" y="57" textAnchor="end">100%</text></svg>}<p className="chart-takeaway">{takeaway}</p><ProofReference id={id} onProof={onProof}/><Table caption={`${source(id).label}; ${metric(ids[0]).attribution}`} headers={['Measure','Value','Unit']} rows={ids.map(mid=>{const m=metric(mid);return [m.label,m.display,m.unit];})}/></div></section>;
}
export function AgeChart({onProof}:{onProof:Proof}){
  const [active,setActive]=useState<string|null>(null);
  const {audience}=content;
  return <section className="chart-panel age-chart" onKeyDown={e=>{if(e.key==='Escape')setActive(null);}} aria-labelledby="age-heading"><div className="chart-heading"><h4 id="age-heading">Understand who is following.</h4><span className="caption">Share of Instagram followers by age</span></div><p className="chart-period">May 31-Jul 30, 2026</p><div className="age-rows">{audience.rows.map(r=><button className="age-row" key={r.label} aria-label={`${r.label}: ${r.value.toFixed(1)} percent of followers`} onMouseEnter={()=>setActive(r.label)} onMouseLeave={()=>setActive(null)} onFocus={()=>setActive(r.label)} onBlur={()=>setActive(null)} onClick={()=>setActive(r.label)}><span className="age-label">{r.label}</span><svg viewBox="0 0 550 24" aria-hidden="true"><rect width="550" height="12" y="6" rx="6" className="chart-track"/><rect width={r.value/60*550} height="12" y="6" rx="6" className={`chart-fill ${r.value===54?'emphasis':''}`}/></svg><strong>{r.value.toFixed(1)}%</strong>{active===r.label&&<span className="age-tooltip" role="status">{r.label} years: {r.value.toFixed(1)}% of followers</span>}</button>)}</div><p className="chart-axis">Scale: 0-60% of followers</p><p className="chart-takeaway">54.0% of followers were aged 18-24. This supports student-focused planning; it describes followers, not all viewers.</p><ProofReference id="divia-audience" onProof={onProof}/><Table caption="Divia Instagram follower age composition, May 31-Jul 30, 2026" headers={['Age range','Share of followers']} rows={audience.rows.map(r=>[r.label,`${r.value.toFixed(1)}%`])}/></section>;
}
export const tirizOptions=[{id:'tiriz-stories',label:'Stories'},{id:'tiriz-videos',label:'Videos'},{id:'tiriz-feed-reach',label:'Feed reach'},{id:'tiriz-kol-average',label:'Creator views'}];
export function TirizChart({onProof}:{onProof:Proof}){
  const [selected,choose]=useUrlChoice('tiriz',tirizOptions.map(o=>o.id),'tiriz-feed-reach');
  const [tip,setTip]=useState<string|null>(null);
  const m=metric(selected),target=m.target!,max=Math.max(target,m.value)*1.16;
  const pct=m.value/target*100;
  return <section className="chart-panel tiriz-chart" onKeyDown={e=>{if(e.key==='Escape')setTip(null);}} aria-labelledby="tiriz-chart-heading"><div className="chart-heading"><h4 id="tiriz-chart-heading">Delivery is only half the story.</h4><span className="caption">Oct 1-Nov 30, 2025 / Pancarona team campaign</span></div><Tabs id="tiriz" values={tirizOptions} value={selected} onChange={v=>{choose(v);setTip(null);}}/><div id="tiriz-panel" role="tabpanel" aria-labelledby={`tiriz-${selected}`} tabIndex={0}><div className="chart-result"><strong>{format(m.value)}</strong><span>{m.unit}</span><p>{format(pct,selected==='tiriz-feed-reach'?2:selected==='tiriz-kol-average'?1:0)}% of target <span className="status-label">{m.value>=target?'Target exceeded':'Below target'}</span></p></div><div className="comparison-bars">{[{label:'Target',value:target},{label:'Actual',value:m.value}].map((r,i)=><button className="comparison-row" key={r.label} onMouseEnter={()=>setTip(r.label)} onMouseLeave={()=>setTip(null)} onFocus={()=>setTip(r.label)} onBlur={()=>setTip(null)} onClick={()=>setTip(r.label)} aria-label={`${r.label}: ${format(r.value)} ${m.unit}`}><span>{r.label}</span><svg viewBox="0 0 700 44" aria-hidden="true"><rect x="0" y="8" width="700" height="28" rx="6" className="chart-track"/><rect x="0" y="8" width={r.value/max*700} height="28" rx="6" className={i===0?'chart-target':'chart-fill'}/></svg><strong>{format(r.value)}</strong>{tip===r.label&&<span className="bar-tooltip" role="status">{r.label}: {format(r.value)} {m.unit}</span>}</button>)}</div><p className="chart-axis">Separate scale for {m.unit}: 0-{format(max,0)}</p><p className="chart-takeaway">{selected==='tiriz-feed-reach'?'Average feed reach missed the target by 185.9 accounts per post. More content did not guarantee stronger reach.':selected==='tiriz-stories'?'120 Stories against a target of 40: 300% of target. Content volume exceeded the plan.':selected==='tiriz-videos'?'16 short-form videos against a target of 8: 200% of target. Reels were mirrored to TikTok.':'69,024 views across four creator pieces averaged 17,256 views. That is 1,725.6% of target, or 1,625.6% above target.'}</p><ProofReference id="tiriz-kpi" onProof={onProof}/><Table caption="TIRIZ campaign, Oct 1-Nov 30, 2025; team/account outcomes; separate units and scales" headers={['Measure','Unit','Target','Actual','% of target']} rows={tirizOptions.map(o=>{const t=metric(o.id);return [t.label,t.unit,format(t.target!),format(t.value),`${format(t.value/t.target!*100,t.id==='tiriz-feed-reach'?2:t.id==='tiriz-kol-average'?1:0)}%`];})}/></div></section>;
}
