import React from 'react';
import ReactDOM from 'react-dom/client';
import '@fontsource/silkscreen/latin-400.css';
import '@fontsource/source-sans-3/latin-400.css';
import '@fontsource/source-sans-3/latin-600.css';
import '@fontsource/source-sans-3/latin-700.css';
import App from './App';
import './styles.css';
const root=document.getElementById('root')!;
if(root.hasChildNodes())ReactDOM.hydrateRoot(root,<React.StrictMode><App/></React.StrictMode>);
else ReactDOM.createRoot(root).render(<React.StrictMode><App/></React.StrictMode>);
